# Generated by Django 4.2.1 on 2023-05-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0009_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
